name: deploy 
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup npm
        uses: actions/setup-node@v3
        with:
          node-version: '14.X'
      - name: 下载依赖
        run: npm install
      - name: build
        run: npm run build
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWD }}
          port: 22
          source: 'dist/index.html'
          target: ${{ secrets.TARGET }}
          overwrite: true
          
